source ~/.vim/vundle.vim
source ~/.vim/global.vim
source ~/.vim/status_bar.vim
source ~/.vim/keybindings.vim
source ~/.vim/operate_on_indent_levels.vim
source ~/.vim/autocomplete.vim
source ~/.vim/promote_to_let.vim
source ~/.vim/file_search.vim
source ~/.vim/abbreviations.vim
source ~/.vim/ctl-p.vim
source ~/.vim/go.vim
source ~/.vim/nerdtree.vim
